{% set name = "pandas-profiling" %}
{% set version = "3.0.0" %}
{%set hash_type = "md5" %}
{% set hash_val = "00094dbcfbbca1457b2b0bfc95a5ba4f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - scipy >=1.4.1
    - requests >=2.24.0
    - pydantic >=1.8.1
    - pyyaml >=5.0.0
    - missingno >=0.4.2
    - pandas >=0.25.3,!=1.0.1,!=1.0.0,!=1.0.2,!=1.1.0
    - matplotlib-base >=3.2.0
    - jinja2 >=2.11.1
    - htmlmin >=0.1.12
    - phik >=0.11.1
    - confuse >=1.0.0
    - visions 0.7.1
    - numpy >=1.16.0
    - tangled-up-in-unicode >=0.0.7
    - tqdm >=4.48.2
    - ipywidgets >=7.5.1
    - imagehash
    - pillow
    - seaborn >=0.10.1
    - joblib
    - ipython
    - markupsafe >=1.1.1
    - multimethod >=1.4

test:
  imports:
    - pandas_profiling
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/pandas-profiling/pandas-profiling
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate profile report for pandas DataFrame
  dev_url: http://github.com/pandas-profiling/pandas-profiling
  doc_url: https://pandas-profiling.github.io/pandas-profiling/docs/

extra:
  recipe-maintainers:
    - sbrugman
    - proinsias
    - philip-khor