{% set name = "pandas-profiling" %}
{% set version = "2.13.0" %}
{%set hash_type = "md5" %}
{% set hash_val = "93a05446831534536ae4f2976eb75071" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
     - pandas_profiling = pandas_profiling.controller.console:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy >=1.4.1
    - joblib
    - pandas >=0.25.3,!=1.0.1,!=1.0.0,!=1.0.2,!=1.1.0
    - matplotlib-base >=3.2.0
    - pydantic >=1.8.1
    - pyyaml >=5.0.0
    - jinja2 >=2.11.1
    - confuse >=1.0.0
    - visions ==0.7.0
    - numpy >=1.16.0
    - attrs >=19.3.0
    - ipywidgets >=7.5.1
    - requests >=2.24.0
    - tqdm >=4.48.2
    - imagehash
    - missingno >=0.4.2
    - htmlmin >=0.1.12
    - phik >=0.11.1
    - seaborn >=0.10.1
    - tangled-up-in-unicode >=0.0.7

test:
  imports:
    - pandas_profiling
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pandas-profiling/pandas-profiling
  license: MIT
  license_file: LICENSE
  summary: Generate profile report for pandas DataFrame
  dev_url: http://github.com/pandas-profiling/pandas-profiling
  doc_url: https://pandas-profiling.github.io/pandas-profiling/docs/

extra:
  recipe-maintainers:
    - sbrugman
    - proinsias
    - philip-khor
