{% set name = "pandas-profiling" %}
{% set version = "1.3.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "53244ffc5e924fe702d599fba13988268257207e45b104ccbb2f922458c9591e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pandas >=0.16
    - matplotlib >=1.4
    - jinja2 >=2.8
    - six >=1.9

test:
  imports:
    - pandas_profiling

about:
  home: http://github.com/jospolfliet/pandas-profiling
  license: MIT
  license_file: LICENSE
  summary: 'Generate profile report for pandas DataFrame'
  dev_url: http://github.com/jospolfliet/pandas-profiling

extra:
  recipe-maintainers:
    - proinsias
