travis:
  secure:
    BINSTAR_TOKEN: N5enwT+MlI6gOXR5P/1XYnBbI2yJt1I6wEJdgN7+Pkb/BDr109EllOXB7cMCGm/un4A05IW9qhQs7M7W/bKV5FZk+jDiUq5J1cODp04q8KiUf2sxN+BEhuwSc8Rr8byHu4irLE+QoJjXj6N7z04HXRUXyP+V9WRYnDAIRAG9NXCQd+yvFETXBwJ8wxcGNfFiuyjERWvKWh0vX8GIFhqCrYazEr6xfDuzbF8M8CAWgR4V3eFCb+qOVS1EEo4p1uP9hHiu/uNs0e/4L8H6EgUt+QQ7Af+kTcrPQhJNqN40ZvnyytRIPOT0/9IOmfNqL2VrbCW8myHSULyV7diMy1F0YoOySz69IaySQojYkNqjZZDy8ytamDhC5AXIpdQ3zviF7L8224RaEUsyoYXHiyj1Z4a6SK3cCbvH2XSVJuWN8qbhlJvJUarzbXQLb6I99W7ukcw9OWO7Dzh+Kz/riYgiZmQ+ajmPLTUkliYg8AY8Kygt6BPk2DcQ8cPZ16ec/d5bvBnIn4gBENmbLHjKS272ZwmRwsCyPJbAXsk9cSbdvk9lGTeiak5iVpx0ZUHzKobRVn8pym+dRJKpDaDT+a7PMz10VFXjKZEoAv3aV7Y7WL6QUQVNQWVtci1O3vqMEXapqwRQ84jb4XVTNSv3O+RN35MHxyZE7rp7AGRoDoFe4C4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
