travis:
  secure:
    BINSTAR_TOKEN: MCBqUP9UfKN3eFf7t0l8FTTnjQ3OpT4oij8QmCVYFK/lQpXkGVEsA9/Q4Ltt04kBMbxzT15uOuCxgEmpYQZV+AXsL+T3Kxrf9jQvw0MPA7cIp8p72fovA6kdCRJA1qYG8pboVBMBoAHASoM7Az22uaFh239ML1CYdgLXWWi9LsRs2Ap9ry0SYyGlLpVieW1cuz6m0mNOvrqfVMdjX0wOI4JnH19nElBFnvXwpdvT/aF3J2s9x/1CMPMuzT8NGBbbwssWG75WSyo4oDNfy9Di2m7n1v2D1IZM8g0iiWJELSn7joozVQnVEUCgU3HD4UkOl5dmluy3cya0ubziB3ywqoJzpiRv+OxpNQhBxwBp8OEMlR53d0ocf/T3g5cxc+nL4XEeSYlAJqM4H3lG4HrSKjbr3qt2TKhYM9dPiW5+Qq+4V1H3c5pLap3zJpPvMccTxhXsxKJFgFXGVbLkHah5LZd+0z7tjEpGrKl5+/4KRNTV32sLcZd1JqrTMu/v6jEBYhJtrjUcIGk9rhU3V84KT/UABxUyoovTrO2wyICGPb/ACxv9U0yf+3aAxMiD7CiAjEmV7nNV4lVVo9dQMDpAiTDE3pEAKuxGJBd4QHa0AIj9Wxx2IJZz9c63KM+uQY++fskRwQy4DsedfDzG7oPqt8h5Zi1z7Jetuu0I4jSmIHA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
