travis:
  secure:
    BINSTAR_TOKEN: rDquwhOtyKNotLxt/qtXDEh1kWBs1u2c/yuPPZFFARdapIPgbJitEldbeQjrPaeCdrejdBRQA+biPBZ58fsg44oLBIfA0pYypOtIti0fMzUKq+jvrVOV/N7b1HHAt0wU5P4K9Y/K/Jhaekrtw8SF2OIjkDjhxBy82n8Lf3uf/m8Sr3P0IQbUCawzhLF4TF7txZCKYZqZE6Q8wJMXvo8p75sqi2ag/pcwmrqOInRRA/lgrfOM4QE/P5GkqqDE/EyaQydsnPDaygVb9Z4yma9myGbBe+VLuS+2hOIPcaNYZoLZ2B7YuCO74amkpoq1/9lj+HMy65wCqhn2nBjqFM2oOIeHkmJ2S/zqHbbr5WnaVk+IM/7+b7MDb8bKnw03KLFR6+RNFEOjYrqW8Rlkz8W4Tvo3BtEynCAlealooqOEnU5B0XZDJgL288kYDadnnvBtRIy00Jm6UWCjfAexsXRdJiBs5caukP67Ju+pRCE+3xspynfH6DyRUdikhCfmWxLlA0H9E7nG0sQn9V1giVl0Iqm/LOAERUegGNqHNzNMkREMohDkXbcJf0Xb0gDiEfG7VMKaabHSO/66WLgtgfpXsgn83+n0OrZC9yaa+OrdRiJ4SFoxYIAIAZeqnflT5vDUu5YqUIoUcz7k2z3vYRkJxGyfg34KnioHs+IbSqnwkDw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
